/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lab2;

import java.awt.Color;
import javax.swing.JFrame;

/**
 *
 * @author juluc
 */
public class FramePrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FramePrincipal
     */


    public FramePrincipal() {
        initComponents();
        buttonCrypto.setBackground(Color.cyan);
        buttonFirewall.setBackground(Color.cyan);
        buttonSecLog.setBackground(Color.cyan);
        buttonPhyshing.setBackground(Color.cyan);
        actualizar();
        this.setLocationRelativeTo(null);
        //setExtendedState(JFrame.MAXIMIZED_BOTH);
         this.getContentPane().setBackground(new Color(0x0A0F18));
        this.setBackground(new Color(0x0A0F1D)); 
         Musica.reproducirMenu();
    }
    
    
    private void actualizar() {
    labelPuntaje.setText("Puntaje:"+Main.calcularPuntajeGlobal());
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        labelvector = new javax.swing.JLabel();
        labelPuntaje = new javax.swing.JLabel();
        Adelante = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        panelLateral = new javax.swing.JPanel();
        buttonPhyshing = new javax.swing.JButton();
        buttonFirewall = new javax.swing.JButton();
        buttonCrypto = new javax.swing.JButton();
        buttonSecLog = new javax.swing.JButton();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(15, 23, 42));
        setForeground(java.awt.Color.blue);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(15, 23, 42));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 153, 153)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lab2/images/moto.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 500, 450, -1));

        jLabel1.setFont(new java.awt.Font("ROG Fonts", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(56, 189, 248));
        jLabel1.setText("GRID PROTOCOL");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, 390, 50));

        jLabel2.setFont(new java.awt.Font("ROG Fonts STRIX SCAR", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(226, 232, 240));
        jLabel2.setText("Eventos Analizados:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 280, 60));

        jLabel3.setFont(new java.awt.Font("ROG Fonts STRIX SCAR", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(226, 232, 240));
        jLabel3.setText("Vectores de ataque:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 280, 300, 50));

        labelvector.setFont(new java.awt.Font("ROG Fonts", 2, 18)); // NOI18N
        labelvector.setForeground(new java.awt.Color(204, 0, 51));
        labelvector.setText("4");
        jPanel1.add(labelvector, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 340, 90, 60));

        labelPuntaje.setFont(new java.awt.Font("ROG Fonts STRIX SCAR", 0, 18)); // NOI18N
        labelPuntaje.setForeground(new java.awt.Color(0, 153, 153));
        labelPuntaje.setText("LabelPuntaje");
        jPanel1.add(labelPuntaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, 240, 70));

        Adelante.setFont(new java.awt.Font("ROG Fonts STRIX SCAR", 1, 24)); // NOI18N
        Adelante.setForeground(new java.awt.Color(255, 255, 255));
        Adelante.setText("TRAIN IN THE GRID. EVOLVE OR DISAPPEAR.");
        jPanel1.add(Adelante, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, 690, 50));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lab2/images/fondozul.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 10, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, 930, 880));

        panelLateral.setBackground(new java.awt.Color(30, 41, 59));
        panelLateral.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(96, 165, 250)));
        panelLateral.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelLateralMouseEntered(evt);
            }
        });
        panelLateral.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonPhyshing.setFont(new java.awt.Font("ROG Fonts STRIX SCAR", 0, 12)); // NOI18N
        buttonPhyshing.setText("Phish Hunter");
        buttonPhyshing.setPreferredSize(new java.awt.Dimension(90, 20));
        buttonPhyshing.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonPhyshingMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonPhyshingMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonPhyshingMouseExited(evt);
            }
        });
        panelLateral.add(buttonPhyshing, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 200, 40));

        buttonFirewall.setFont(new java.awt.Font("ROG Fonts STRIX SCAR", 0, 12)); // NOI18N
        buttonFirewall.setText("Firewall Catching");
        buttonFirewall.setMaximumSize(new java.awt.Dimension(90, 20));
        buttonFirewall.setMinimumSize(new java.awt.Dimension(90, 19));
        buttonFirewall.setPreferredSize(new java.awt.Dimension(90, 23));
        buttonFirewall.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonFirewallMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonFirewallMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonFirewallMouseExited(evt);
            }
        });
        panelLateral.add(buttonFirewall, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 200, 40));

        buttonCrypto.setFont(new java.awt.Font("ROG Fonts STRIX SCAR", 0, 12)); // NOI18N
        buttonCrypto.setText("Crypto Breaker");
        buttonCrypto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonCryptoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonCryptoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonCryptoMouseExited(evt);
            }
        });
        panelLateral.add(buttonCrypto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 200, 40));

        buttonSecLog.setFont(new java.awt.Font("ROG Fonts STRIX SCAR", 2, 12)); // NOI18N
        buttonSecLog.setText("Secure Log");
        buttonSecLog.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonSecLogMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonSecLogMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonSecLogMouseExited(evt);
            }
        });
        panelLateral.add(buttonSecLog, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 200, 40));

        getContentPane().add(panelLateral, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 230, 870));

        Fondo.setBackground(new java.awt.Color(15, 23, 42));
        Fondo.setForeground(new java.awt.Color(15, 23, 42));
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 900));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void panelLateralMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelLateralMouseEntered
  ;        // TODO add your handling code here:
    }//GEN-LAST:event_panelLateralMouseEntered

    private void buttonPhyshingMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonPhyshingMouseEntered
       buttonPhyshing.setBackground(Color.red);        // TODO add your handling code here:
    }//GEN-LAST:event_buttonPhyshingMouseEntered

    private void buttonPhyshingMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonPhyshingMouseExited
 buttonPhyshing.setBackground(Color.cyan);        // TODO add your handling code here:
    }//GEN-LAST:event_buttonPhyshingMouseExited

    private void buttonFirewallMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonFirewallMouseEntered
        buttonFirewall.setBackground(Color.red);
    }//GEN-LAST:event_buttonFirewallMouseEntered

    private void buttonFirewallMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonFirewallMouseExited
       buttonFirewall.setBackground(Color.cyan);
    }//GEN-LAST:event_buttonFirewallMouseExited

    private void buttonCryptoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonCryptoMouseEntered
         buttonCrypto.setBackground(Color.red);
    }//GEN-LAST:event_buttonCryptoMouseEntered

    private void buttonCryptoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonCryptoMouseExited
        
        buttonCrypto.setBackground(Color.cyan);
    }//GEN-LAST:event_buttonCryptoMouseExited

    private void buttonSecLogMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonSecLogMouseClicked
        FrameSec frame = new FrameSec();
        frame.setVisible(true);
        
        FramePrincipal.this.setVisible(false);
        
    }//GEN-LAST:event_buttonSecLogMouseClicked

    private void buttonSecLogMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonSecLogMouseEntered
        
        buttonSecLog.setBackground(Color.red);
        
    }//GEN-LAST:event_buttonSecLogMouseEntered

    private void buttonSecLogMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonSecLogMouseExited
        
        buttonSecLog.setBackground(Color.cyan);
    }//GEN-LAST:event_buttonSecLogMouseExited

    private void buttonFirewallMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonFirewallMouseClicked
       FirewallMatrix frame = new FirewallMatrix();
        frame.setVisible(true);
        FramePrincipal.this.setVisible(false);
    }//GEN-LAST:event_buttonFirewallMouseClicked

    private void buttonPhyshingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonPhyshingMouseClicked
        FramePhishHunter frame = new FramePhishHunter();
        frame.setVisible(true);
        FramePrincipal.this.setVisible(false);
    }//GEN-LAST:event_buttonPhyshingMouseClicked

    private void buttonCryptoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonCryptoMouseClicked
        FrameCryptoBreaker frame = new FrameCryptoBreaker();
        frame.setVisible(true);
        FramePrincipal.this.setVisible(false);
    }//GEN-LAST:event_buttonCryptoMouseClicked

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FramePrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Adelante;
    private javax.swing.JLabel Fondo;
    private javax.swing.JButton buttonCrypto;
    private javax.swing.JButton buttonFirewall;
    private javax.swing.JButton buttonPhyshing;
    private javax.swing.JButton buttonSecLog;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelPuntaje;
    private javax.swing.JLabel labelvector;
    private javax.swing.JPanel panelLateral;
    // End of variables declaration//GEN-END:variables
}
